#@ load("@ytt:data", "data")
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VCDCluster
metadata:
  name: #@ data.values.cluster.name
  namespace: #@ data.values.cluster.namespace
spec:
  site: #@ data.values.vcd.url
  org: #@ data.values.vcd.org
  ovdc: #@ data.values.vcd.ovdc
  ovdcNetwork: #@ data.values.vcd.ovdcNetwork
  userContext:
    refreshToken: #@ data.values.vcd.refreshToken
  defaultStorageClassOptions:
    vcdStorageProfileName: #@ data.values.storage.vdcStoragePolicy
    k8sStorageClassName: #@ data.values.storage.k8sClassName
    #@ if data.values.storage.reclaimPolicy == "delete":
    useDeleteReclaimPolicy: true 
    #@ else:
    useDeleteReclaimPolicy: false
    #@ end

    fileSystem: ext4

