#@ load("@ytt:data", "data")
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: #@ data.values.cluster.name + "-workers0"
  namespace: #@ data.values.cluster.namespace
spec:
  template:
    spec:
      users:
      - name: root
        sshAuthorizedKeys:
        - #@ data.values.cluster.sshKey
      joinConfiguration:
        nodeRegistration:
          criSocket: /run/containerd/containerd.sock
          kubeletExtraArgs:
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
            cloud-provider: external
