#@ load("@ytt:data", "data")
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: #@ data.values.cluster.name + "-workers0"
  namespace: #@ data.values.cluster.namespace
spec:
  clusterName: #@ data.values.cluster.name
  replicas:  #@ data.values.workers.count 
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: #@ data.values.cluster.name + "-workers0"
          namespace: #@ data.values.cluster.namespace
      clusterName: #@ data.values.cluster.name
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VCDMachineTemplate
        name: #@ data.values.cluster.name + "-workers0" 
        namespace: #@ data.values.cluster.namespace
      version: #@ data.values.cluster.version
